require("dotenv").config();

const {
  FIREBASE_ADMIN_CONFIG,
  FIREBASE_APP_CONFIG,
  BCON_API_KEY,
  COINPAYMENTS_API_KEY,
  COINPAYMENTS_API_SECRET,
  TESTING
} = process.env;

module.exports = {
  FIREBASE_ADMIN_CONFIG,
  FIREBASE_APP_CONFIG,
  BCON_API_KEY,
  COINPAYMENTS_API_KEY,
  COINPAYMENTS_API_SECRET,
  TESTING
};
